### PR TITLE
Fix incorrect capitalization

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by JCEmmons** [comment]
CLDR Does NOT accept pull requests for the JSON form of the data, as the XML form is the official format. See <https://github.com/unicode-cldr/cldr-json> for additional information about how to submit corrections to the CLDR data

**Comment by revolter** [comment]
And [these steps](http://cldr.unicode.org/development/new-cldr-developers) are required for contributing to CLDR?

**Comment by revolter** [comment]
Also, https://nopullrequests.appspot.com

**Comment by JCEmmons** [comment]
Thanks for the info about the no pull requests bot - we probably should look into it.

For simple corrections like the ones you mention, probably easiest is just to open a new ticket at <http://unicode.org/cldr/trac/newticket> and put the necessary information there.

If you are planning to do larger scale contributions, you will want to participate in CLDR's annual survey process. See <http://cldr.unicode.org/index/survey-tool> for info on that.

**Comment by revolter** [comment]
@JCEmmons, I can't! That stupid issue tracker returns this error:

> Submission rejected as potential spam (BotScout says this is spam (Y|MULTI|IP|1|MAIL|0|NAME|0))

**Comment by revolter** [comment]
It keeps marking it as spam. God this is annoying. Working so hard just to help you :|

**Comment by JCEmmons** [comment]
Sent a msg to our Trac person on the Unicode side to see why it's 
rejecting....


Regards,

John C. Emmons
Globalization Architect & Unicode CLDR TC Vice Chairman
IBM Globalization Team
e-mail: emmo@us.ibm.com

**Comment by srl295** [comment]
@revolter thank you for your persistence… https://unicode.org/cldr/trac/ticket/11222

**Comment by srl295** [comment]
> nopullrequests

Ha, i just tried to open an Issue on this repo to install that.. and i couldn't...

**Comment by revolter** [comment]
@srl295, And thank you for the help. Will I receive emails on replies?

> Ha, i just tried to open an Issue on this repo to install that.. and i couldn't...

Shouldn't you open an internal issue?

**Comment by srl295** [comment]
@revolter 
> Shouldn't you open an internal issue?

CLDR has no internal, all public.

**Pull request closed without merging**
